server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # SQL 쿼리를 보기 좋게 포맷팅하여 로그에 출력
    show-sql: true # 실행되는 SQL 쿼리를 로그에 출력

  config:
    import: optional:env.yml

management:
  server:
    port: 9292
  endpoints:
    web:
      exposure:
        include: health, info

  endpoint:
    health:
      show-details: when_authorized
  info:
    java:
      enabled: true
    os:
      enabled: true
    git:
      mode: "full"
    build:
      enabled: true

gemini:
  api:
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent
    key: ${GEMINI_API_KEY}
  generation:
    temperature: 0.5
    max-output-tokens: 8192

chatgpt:
  api:
    url: https://api.openai.com/v1/chat/completions
    key: ${CHATGPT_API_KEY}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  client-secret: ${KAKAO_CLIENT_SECRET}
  allowed-redirect-uris: ${KAKAO_ALLOWED_REDIRECT_URIS:}

toss:
  client-key: ${TOSS_CLIENT_KEY}
  secret-key: ${TOSS_SECRET_KEY}
  widget-secret-key: ${TOSS_WIDGET_SECRET_KEY}
  api:
    url: https://api.tosspayments.com

jwt:
  token:
    secretKey: ${JWT_TOKEN_SECRETKEY}

logging:
  level:
    org:
      hibernate:
        SQL: debug # SQL과 파라미터를 함께 로그에 출력
