jwt:
  token:
    secretKey: ${JWT_TOKEN_SECRETKEY}

logging:
  level:
    org:
      springframework:
        jdbc: debug
        security: info
    com.zaxxer.hikari: INFO

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  client-secret: ${KAKAO_CLIENT_SECRET}